### ISSUE TITLE
Wrong resultset result

### ISSUE THREAD

**Issue by kendarorg** [kendarorg/HttpAnsweringMachine#128]
Start dbproxy
Initialize db
Create recording
Restart be
Save recording
Play recording
Restart be

Caused by: java.lang.ClassCastException: class org.kendar.janus.results.ObjectResult cannot be cast to class org.kendar.janus.JdbcResultSet (org.kendar.janus.results.ObjectResult and org.kendar.janus.JdbcResultSet are in unnamed module of loader 'app')
        at org.kendar.janus.JdbcDatabaseMetaData.getTables(JdbcDatabaseMetaData.java:1033) ~[janus-driver-1.0.11-SNAPSHOT.jar:na]
        at com.zaxxer.hikari.pool.ProxyDatabaseMetaData.getTables(ProxyDatabaseMetaData.java:68) ~[HikariCP-4.0.3.jar!/:na]
        at com.zaxxer.hikari.pool.HikariProxyDatabaseMetaData.getTables(HikariProxyDatabaseMetaData.java) ~[HikariCP-4.0.3.jar!/:na]
        at org.hibernate.tool.schema.extract.internal.InformationExtractorJdbcDatabaseMetaDataImpl.processTableResultSet(InformationExtractorJdbcDatabaseMetaDataImpl.java:64) ~[hibernate-core-5.6.4.Final.jar!/:5.6.4.Final]
        at org.hibernate.tool.schema.extract.internal.AbstractInformationExtractorImpl.getTables(AbstractInformationExtractorImpl.java:555) ~[hi

**Comment by kendarorg** [comment]
Solved rewriting the db request engine
